meta-freescale: disable multilib 32-bit for package rcw
Issue: LIN1018-4674

The rcw package is existed with u-boot and other necessary
firmwares, which are all based on 64-bit. So disable multilib
32-bit building for the package, and to avoid below build error:

ERROR: lib32-rcw-git-r0 do_deploy: The recipe lib32-rcw is trying to
install files into a shared area when those files already exist.
Those files and their manifest location are

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>