meta-freescale: install missing header file when build ceetm
Issue: US118835

fix below building error:

ceetm/git-r0/recipe-sysroot/usr/include/tc/tc_util.h:14:10: fatal error:
json_print.h: No such file or directory
|  #include "json_print.h"
|           ^~~~~~~~~~~~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>