drop nativesdk-packagegroup-sdk-host.bbappend
Issue: LIN10-3030

The NXP sdk packagegroup is not needed for WRLinux release. To reserve
the built error like below:

ERROR: Nothing RPROVIDES 'nativesdk-mxsldr'
(but layers/oe-core/meta/recipes-core/packagegroups/nativesdk-packagegroup-sdk-host.bb RDEPENDS on or otherwise requires it)

(LOCAL REV: NOT UPSTREAM) -- Only exists in WRL.

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>